apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::347701720649:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-kInfcDo5YOZx
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::347701720649:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-14T04:28:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3886"
  uid: bcc78180-66f2-4f04-aa49-826da065829a
